from django.urls import path
from .views import (
    BusinessTractionView,
    CheckoutPublicVisitorView,
    CheckoutPrivateVisitorView,
    FoundersView,
    FounderConfirmView,
    FounderEditView,
    FounderDeleteView,
    StartupView, 
    StartupCategoryView,
    StartupCategoryTechSectorView,
    StartupEditLocation, 
    StartupEditStage, 
    StartupEditFoundationDate,
    StartupEditIndustry, 
    StartupEditName,
    StartupEditView,
    StartupEditWebsite,
    StartupImageEdit,
    StartupEditVideo, 
    StartupEditDescription,
    StartupEditPitchDeckUpload,
    StartupPrivacyView,
    StartupShareView,
    StartupPublicView,
    StartupPrivateView
)


urlpatterns = [
    path('startup/', StartupView.as_view(), name='startup'),
    path('startup/<str:startupId>/edit/',StartupEditView.as_view(),name="startup-edit"),
    path('startup/<str:startupId>/edit-stage/',StartupEditStage.as_view(), name='startup-edit-stage'),
    path('startup/<str:startupId>/edit-privacy/',StartupPrivacyView.as_view(), name='startup-edit-privacy'),
    path('startup/<str:startupId>/edit-location/', StartupEditLocation.as_view(), name='startup-edit-location'),
    path('startup/<str:startupId>/edit-industry/', StartupEditIndustry.as_view(), name='startup-edit-industry'),
    path('startup/<str:startupId>/edit-name/', StartupEditName.as_view(), name='startup-edit-name'),
    path('startup/<str:startupId>/edit-website/', StartupEditWebsite.as_view(), name='startup-edit-website'),
    path('startup/<str:startupId>/edit-image/', StartupImageEdit.as_view(), name='startup-edit-image'),
    path('startup/<str:startupId>/edit-video/', StartupEditVideo.as_view(), name='startup-edit-video'),
    path('startup/<str:startupId>/edit-description/', StartupEditDescription.as_view(), name='startup-edit-description'),
    path('startup/<str:startupId>/edit-foundation-date/',StartupEditFoundationDate.as_view(),name='startup-edit-foundation-date'),
    path('startup/<str:startupId>/edit-pitchdeck/', StartupEditPitchDeckUpload.as_view(), name='startup-create-pitchdeck'),
    path('startup/<str:startupId>/founders/', FoundersView.as_view(), name='founders'),
    path('startup/<str:startupId>/founders/<int:founderId>/confirm/', FounderConfirmView.as_view(),name='founder-confirm'),
    path('startup/<str:startupId>/founders/<int:founderId>/edit/', FounderEditView.as_view(),name='founder-edit'),
    path('startup/<str:startupId>/founders/<int:founderId>/delete/',FounderDeleteView.as_view(),name='founder-delete'),
    path('startup/<str:startupId>/business-traction/', BusinessTractionView.as_view(), name='business-traction'),
    path('startup/<str:startupId>/share/', StartupShareView.as_view(), name='share'),
    path('startup/<str:startupId>/public/', StartupPublicView.as_view(), name='public-view'),
    path('startup/<str:startupId>/<str:email>/<str:token>/private/', StartupPrivateView.as_view(), name='private-view'),
    path('startup/<str:startupId>/check-public-visitor/',CheckoutPublicVisitorView.as_view(),name="check-public-visitor"),
    path('startup/<str:startupId>/<str:email>/<str:token>/check-private-visitor/',CheckoutPrivateVisitorView.as_view(),name="check-private-visitor"),
    path('startup/categories/', StartupCategoryView.as_view(), name='startup-categories' ),
    path('startup/tech-sectors/', StartupCategoryTechSectorView.as_view(), name='startup-tech-sectors'),
]
