# Generated by Django 4.2.11 on 2024-09-04 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_status', models.CharField(choices=[('trial', 'Trail'), ('basic', 'Basic'), ('pro', 'Pro')], default='Trial', max_length=100)),
                ('stripe_trial_end_date', models.DateTimeField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startups.startup')),
            ],
        ),
    ]
