# Generated by Django 4.2.11 on 2024-09-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_status',
            field=models.CharField(choices=[('trial', 'trial'), ('basic', 'basic'), ('pro', 'pro')], default='trial', max_length=100),
        ),
    ]
