# Generated by Django 4.2.11 on 2024-08-27 05:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('device_id', models.CharField(blank=True, max_length=350, null=True)),
                ('unique_token', models.CharField(max_length=100, unique=True)),
                ('is_terms_acepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PublicVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('device_id', models.CharField(blank=True, max_length=350, null=True)),
                ('is_terms_acepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=150, null=True)),
                ('employee_count', models.CharField(blank=True, choices=[('1 - 10', '1 - 10'), ('10 - 50', '10 - 50'), ('50 - 250', '50 - 250'), ('+ 250', '+ 250')], default='1 - 10', max_length=20, null=True)),
                ('stage', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StartupBusinessTraction',
            fields=[
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='business_tractions', serialize=False, to='startups.startup')),
                ('business_model', models.CharField(blank=True, choices=[('product_sales', 'Product Sales'), ('service_based', 'Service Based'), ('platform', 'Platform'), ('e_commerce', 'E-Commerce'), ('marketplace', 'Marketplace'), ('subcription', 'Subcription'), ('saas', 'Saas'), ('fremium', 'Fremium'), ('other', 'Other')], default='other', max_length=50, null=True)),
                ('business_revenue_sources', models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'SB2C'), ('b2b2c', 'B2B2C')], default='b2b', max_length=20, null=True)),
                ('mrr', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartupVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video', to='startups.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupTopCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='top_customers', to='startups.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupSlidedeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slidedeck', to='startups.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('relationship', models.CharField(max_length=150)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startups.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location', to='startups.startup')),
            ],
        ),
        migrations.CreateModel(
            name='StartupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image', to='startups.startup')),
            ],
        ),
    ]
