# Generated by Django 4.2.11 on 2024-08-27 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='main_founder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_founder_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicvisitor',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_visitors', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='privatevisitor',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_visitors', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='founder',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='founders', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='founder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startuptopcustomer',
            name='business_traction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='top_customers', to='startups.startupbusinesstraction'),
        ),
    ]
