# Generated by Django 4.2.11 on 2024-10-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_remove_startup_industry_startup_industry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='startuplocation',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
