# Generated by Django 4.2.11 on 2024-10-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_startuplocation_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='foundation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupbusinesstraction',
            name='business_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
