# Generated by Django 4.2.11 on 2024-10-31 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_startup_foundation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='tech_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tech_sector', to='startups.startupsubcategory'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.CharField(blank=True, choices=[('Seed', 'Seed'), ('Pre-Seed', 'Pre-Seed'), ('Series A', 'Series A'), ('Series B', 'Series B'), ('Series C', 'Series C'), ('Series D', 'Series D')], max_length=20, null=True),
        ),
    ]
