# Generated by Django 4.2.11 on 2024-11-09 00:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0007_startup_tech_sector_alter_startup_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupTechSector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='startup',
            name='tech_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tech_sector', to='startups.startuptechsector'),
        ),
    ]
