# Generated by Django 4.2.11 on 2024-09-12 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_initial'),
        ('investors', '0005_inversortemporal_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteInvestorsTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.inversortemporal')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='startups.startup')),
            ],
        ),
    ]
