# Generated by Django 4.2.11 on 2024-09-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_remove_startup_industry_startup_industry_category'),
        ('investors', '0006_favoriteinvestorstemporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversortemporal',
            name='industry_categories',
            field=models.ManyToManyField(blank=True, to='startups.startupcategory'),
        ),
    ]
