# Generated by Django 4.2.11 on 2024-08-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('overal_rating', models.IntegerField()),
                ('team_value', models.IntegerField(blank=True, null=True)),
                ('problem_value', models.IntegerField(blank=True, null=True)),
                ('solution_value', models.IntegerField(blank=True, null=True)),
                ('gtmstrategy_value', models.IntegerField(blank=True, null=True)),
                ('marketopp_value', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
